function [fitresult, gof] = createFit(YearFraction, fCO2sw)
%CREATEFIT(YEARFRACTION,FCO2SW)
%  Create a fit.
%
%  Data for 'M1' fit:
%      X Input: YearFraction from m1
%      Y Output: fCO2sw from m1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Jun-2023 12:46:01


%% Fit: 'M1'.
[xData, yData] = prepareCurveData( YearFraction, fCO2sw );

% Set up fittype and options.
ft = fittype( 'a0+c1*(x-2019)+a1*cos(2*x*pi)+b1*sin(2*x*pi)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.22174673401724 0.296675873218327 0.318778301925882 0.117417650855806];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'M1' );
h = plot( fitresult, xData, yData );
legend( h, 'fCO2sw vs. YearFraction', 'M1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'YearFraction', 'Interpreter', 'none' );
ylabel( 'fCO2sw', 'Interpreter', 'none' );
grid on


