function febMarch = importCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FEBMARCH = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  FEBMARCH = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  febMarch = importfile("C:\Users\usuario\Desktop\Renate-files\febMarch.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 13-Apr-2023 11:04:02

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 37);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Type", "error", "PCDate", "PCTime", "GPSDate", "gpsTime", "latitude", "longitude", "equTemp", "stdVal", "CO2aW", "CO2bW", "CO2Umm", "H2OaW", "H2ObW", "H2OMmm", "licorTemp", "licorPress", "atmPress", "equPress", "H2OFlow", "licorFlow", "equPump", "ventFlow", "atmCond", "equCond", "drip1", "NA", "condTemp", "dryBoxTemp", "deckBoxTemp", "IntakeTemp", "TEMP", "SAL", "Oxygen", "Saturation", "Temp"];
opts.VariableTypes = ["categorical", "double", "datetime", "datetime", "datetime", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Type", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "PCDate", "InputFormat", "dd/MM/yyyy");
opts = setvaropts(opts, "PCTime", "InputFormat", "HH:mm:ss");
opts = setvaropts(opts, "GPSDate", "InputFormat", "dd/MM/yyyy");
opts = setvaropts(opts, "gpsTime", "InputFormat", "HH:mm:ss");

% Import the data
febMarch = readtable(filename, opts);

end