function B = importClimate(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  B = IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  B = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  B = importfile1("C:\Users\usuario\Desktop\Renate-files\gando-climate.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-Jun-2023 10:34:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Col1", "Col2"];
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Col1", "Col2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Col1", "Col2"], "EmptyFieldRule", "auto");

% Import the data
B = readtable(filename, opts);

end