function BoyaGando192 = importOptode(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BOYAGANDO192 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  BOYAGANDO192 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  BoyaGando192 = importfile("C:\Users\TESTER\OneDrive\Escritorio\Datos_Boya_Gando\filesOptode\BoyaGando_192.xml", [6, 6]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Feb-2023 13:57:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, 6];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "dateOpt", "VarName3", "VarName4", "VarName5", "VarName6"];
opts.SelectedVariableNames = ["dateOpt", "VarName3", "VarName4", "VarName5", "VarName6"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "dateOpt"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "dateOpt"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "VarName6", "TrimNonNumeric", true);
opts = setvaropts(opts, "VarName6", "ThousandsSeparator", ",");

% Import the data
BoyaGando192 = readtable(filename, opts);

end