function Untitled = importPH(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("C:\Users\usuario\Desktop\Datos_Boya_Gando\0320.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Mar-2023 09:28:26

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["YearDay", "TemperatureC", "SalinityConst", "pHConstSal", "BatteryVoltage", "DateStr", "TimeStr"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "datetime", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "TimeStr", "EmptyFieldRule", "auto");
opts = setvaropts(opts, "DateStr", "InputFormat", "dd/MM/yyyy");
opts = setvaropts(opts, ["YearDay", "TemperatureC", "SalinityConst", "pHConstSal", "BatteryVoltage"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["YearDay", "TemperatureC", "SalinityConst", "pHConstSal", "BatteryVoltage"], "ThousandsSeparator", ".");

% Import the data
Untitled = readtable(filename, opts);

end